const frases = [
    "Yo nunca nunca me he besado con alguien de este grupo.",
    "Yo nunca nunca he tenido sexo en un lugar público.",
    "Yo nunca nunca he coqueteado con un/a desconocido/a solo por diversión.",
    "Yo nunca nunca he mandado fotos desnudo/a a alguien.",
    "Yo nunca nunca he tenido una aventura de una noche.",
    "Yo nunca nunca he hecho algo por debajo de la mesa para salir con alguien.",
    "Yo nunca nunca he tenido un lío amoroso con alguien mayor que yo.",
    "Yo nunca nunca he tenido sexo en un lugar que no fuera mi casa o la de mi pareja.",
    "Yo nunca nunca he besado a alguien por simple presión social.",
    "Yo nunca nunca he jugado a un juego de seducción solo para ver hasta dónde llegaba.",
    "Yo nunca nunca he mandado un mensaje de texto provocativo a alguien sin tener intenciones claras.",
    "Yo nunca nunca he tenido sexo sin protección.",
    "Yo nunca nunca he hecho trampa en un juego de 'verdad o reto'.",
    "Yo nunca nunca he coqueteado con un/a amigo/a solo para ver cómo reaccionaba.",
    "Yo nunca nunca he estado en una relación sin ser completamente honesto/a.",
    "Yo nunca nunca he fingido estar interesado/a en alguien solo para aprovecharme de la situación.",
    "Yo nunca nunca he hablado de mis fantasías sexuales con alguien.",
    "Yo nunca nunca he hecho un comentario provocativo sobre el cuerpo de alguien.",
    "Yo nunca nunca he ido a una fiesta esperando algo más que solo diversión.",
    "Yo nunca nunca he tenido una conversación subida de tono por mensaje de texto.",
    "Yo nunca nunca he tenido una cita a ciegas con alguien que conocí en línea.",
    "Yo nunca nunca he usado un apodo sexy para llamar la atención de alguien.",
    "Yo nunca nunca he tenido pensamientos sexuales con alguien que apenas conocía.",
    "Yo nunca nunca he tenido un crush en alguien mucho mayor que yo.",
    "Yo nunca nunca he hecho que alguien se sintiera incómodo con un comentario subido de tono.",
    "Yo nunca nunca he hecho algo atrevido en público solo para llamar la atención.",
    "Yo nunca nunca he dicho 'te amo' sin sentirlo solo para obtener algo a cambio.",
    "Yo nunca nunca he tenido una discusión sexualmente sugerente con alguien.",
    "Yo nunca nunca he jugado a 'verdad o reto' y elegido un reto sexual.",
    "Yo nunca nunca he coqueteado con alguien solo para ver hasta dónde podía llegar.",
    "Yo nunca nunca he probado juguetes sexuales.",
    "Yo nunca nunca he dado un beso por compromiso.",
    "Yo nunca nunca he fingido estar más interesado/a en alguien solo para que me compraran algo.",
    "Yo nunca nunca he salido con alguien solo porque me gustaba su dinero.",
    "Yo nunca nunca he usado una excusa para salir de una cita aburrida.",
    "Yo nunca nunca he coqueteado con un/a ex para hacer que mi pareja se pusiera celoso/a.",
    "Yo nunca nunca he pasado la noche con alguien sin intenciones de tener sexo.",
    "Yo nunca nunca he rechazado una cita por no querer tener sexo con esa persona.",
    "Yo nunca nunca he usado mi atractivo físico para conseguir algo.",
    "Yo nunca nunca he tenido una conversación íntima con alguien sin haberlo planeado.",
    "Yo nunca nunca he tenido un 'affair' mientras estaba en una relación.",
    "Yo nunca nunca he tenido una discusión sobre sexo con alguien en la que me sintiera incómodo/a.",
    "Yo nunca nunca he hecho que alguien se enamorara de mí solo por diversión.",
    "Yo nunca nunca he coqueteado con alguien solo para conseguir un favor.",
    "Yo nunca nunca he tenido sexo con alguien solo porque estaba borracho/a.",
    "Yo nunca nunca he sentido celos de alguien por su atracción hacia una persona que me gustaba.",
    "Yo nunca nunca he hablado de mi vida sexual con alguien del trabajo.",
    "Yo nunca nunca he coqueteado con alguien por simple diversión.",
    "Yo nunca nunca he tenido sexo en la oficina o en un lugar de trabajo.",
    "Yo nunca nunca he pasado la noche en la casa de alguien sin tener planes de dormir.",
    "Yo nunca nunca he tenido una aventura sexual con un amigo/a cercano/a.",
    "Yo nunca nunca he participado en un juego de 'verdad o reto' que me haya hecho sentir incómodo/a.",
    "Yo nunca nunca he coqueteado con un/a profesor/a o colega solo por diversión.",
    "Yo nunca nunca he tenido sexo con alguien solo para vengarme de otra persona.",
    "Yo nunca nunca he intentado seducir a alguien solo para ver si podía hacerlo.",
    "Yo nunca nunca he usado a alguien para obtener algo material o emocional.",
    "Yo nunca nunca he sentido que me atraía alguien por solo un aspecto físico.",
    "Yo nunca nunca he fingido estar interesado/a en alguien solo para tener sexo.",
    "Yo nunca nunca he pasado tiempo con alguien solo para obtener algo de ellos.",
    "Yo nunca nunca he hecho algo en público para llamar la atención de alguien.",
    "Yo nunca nunca he utilizado a alguien para hacer que otra persona se pusiera celosa.",
    "Yo nunca nunca he coqueteado con alguien solo para ver hasta dónde podía llegar.",
    "Yo nunca nunca he dicho cosas provocativas a alguien para ver su reacción.",
    "Yo nunca nunca he hecho un comentario sobre lo que me gustaría hacer con alguien.",
    "Yo nunca nunca he probado alguna fantasía sexual en la vida real.",
    "Yo nunca nunca he jugado un juego sexual solo por curiosidad.",
    "Yo nunca nunca he jugado lol",
    "Yo nunca nunca me he emputado con alguien de aquí por alguna partida personalizada de lol",
    "Yo nunca nunca me he emputado con alguien de aquí por alguna partida personalizada de lol",
    "Yo nunca nunca me he emputado con alguien de aquí por alguna partida personalizada de lol",
    "Yo nunca nunca me he emputado con alguien de aquí por alguna partida personalizada de lol",
    "Yo nunca nunca me he emputado con alguien de aquí por alguna partida personalizada de lol",
    "Yo nunca nunca me he emputado con alguien de aquí por alguna partida personalizada de lol",
];



function generarFrase() {
    const fraseAleatoria = frases[Math.floor(Math.random() * frases.length)];
    document.getElementById('frase').textContent = fraseAleatoria;
}
